name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug

      # Log in to the GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push the Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v6.16.0
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: ${{ github.ref == 'refs/heads/master' && 'true' || 'false' }}
          tags: |
            ghcr.io/minestudio-host/cors:latest
